// app/Properties/mockProperties.ts

export type Property = {
  id: number;
  title: string;
  price: number;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  location: string;
  imageUrl: string;
  isForSale: boolean;
  description: string;
  details: string;
  LotSize: number;
  HOADues: number;
  YearBuilt: number;
  GarageSqFt: number;
  BasementSqFt: number;
  propertyType: string;
};

export const mockProperties: Property[] = [
  {
    id: 1,
    title: "Spacious Family Villa in Toul Kork",
    price: 350000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2500,
    location: "Toul Kork, Phnom Penh",
    imageUrl: "/assets/images/property.jpg",
    isForSale: true,
    description:
      "A beautiful modern villa perfect for families, located in the heart of Toul Kork.",
    details:
      "Close to international schools and Aeon Mall 2. Includes private garden and parking.",
    LotSize: 4500,
    HOADues: 0,
    YearBuilt: 2017,
    GarageSqFt: 400,
    BasementSqFt: 0,
    propertyType: "Villa",
  },
  {
    id: 2,
    title: "Modern Studio Apartment BKK1",
    price: 65000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 450,
    location: "BKK1, Phnom Penh",
    imageUrl: "/assets/images/property1.jpg",
    isForSale: true,
    description:
      "Fully furnished studio apartment in Phnom Penh’s expat-friendly district.",
    details:
      "Walking distance to cafes, restaurants, and gyms. 24/7 security and pool access.",
    LotSize: 0,
    HOADues: 50,
    YearBuilt: 2019,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Condo",
  },
  {
    id: 3,
    title: "Beachfront Villa",
    price: 270000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    location: "Tonle Mekong, Phnom Penh",
    imageUrl: "/assets/images/property2.jpg",
    isForSale: true,
    description:
      "Charming villa with sea view and direct access to Otres Beach.",
    details:
      "Private garden, large balcony, and secure parking. Perfect for holiday or retirement.",
    LotSize: 3000,
    HOADues: 0,
    YearBuilt: 2015,
    GarageSqFt: 200,
    BasementSqFt: 0,
    propertyType: "Villa",
  },
  {
    id: 4,
    title: "Central Condo Near Riverside",
    price: 120000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 850,
    location: "Daun Penh, Phnom Penh",
    imageUrl: "/assets/images/property3.jpg",
    isForSale: true,
    description:
      "Modern condo with a city view, close to the riverside and night market.",
    details:
      "Ideal for professionals and couples. Gym, swimming pool, and rooftop access.",
    LotSize: 0,
    HOADues: 60,
    YearBuilt: 2020,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Condo",
  },
  {
    id: 5,
    title: "Villa King Borey Chipmong",
    price: 48000,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    location: "Sensok, Phnom Penh",
    imageUrl: "/assets/images/property4.jpg",
    isForSale: true,
    description:
      "Traditional wooden Khmer house surrounded by nature, minutes from Angkor Wat.",
    details: "Peaceful area, perfect for AirBnb rental or family retreat.",
    LotSize: 1600,
    HOADues: 0,
    YearBuilt: 2012,
    GarageSqFt: 50,
    BasementSqFt: 0,
    propertyType: "Traditional",
  },
  {
    id: 6,
    title: "Luxury Penthouse BKK3",
    price: 270000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2100,
    location: "BKK3, Phnom Penh",
    imageUrl: "/assets/images/property5.jpg",
    isForSale: true,
    description:
      "Exclusive penthouse with panoramic views and private rooftop garden.",
    details: "Fully equipped kitchen, high security, and reserved parking.",
    LotSize: 0,
    HOADues: 120,
    YearBuilt: 2021,
    GarageSqFt: 100,
    BasementSqFt: 0,
    propertyType: "Penthouse",
  },
  {
    id: 7,
    title: "Serviced Apartment Sen Sok",
    price: 89000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    location: "Sen Sok, Phnom Penh",
    imageUrl: "/assets/images/property6.jpg",
    isForSale: true,
    description:
      "Spacious serviced apartment in a quiet neighborhood, ideal for families.",
    details: "Includes cleaning service, gym, and kids' playground.",
    LotSize: 0,
    HOADues: 60,
    YearBuilt: 2018,
    GarageSqFt: 60,
    BasementSqFt: 0,
    propertyType: "Apartment",
  },
  {
    id: 8,
    title: "Luxury Villa on Koh Pich",
    price: 530000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3200,
    location: "Koh Pich (Diamond Island), Phnom Penh",
    imageUrl: "/assets/images/property7.jpg",
    isForSale: true,
    description:
      "Stunning luxury villa in the heart of Phnom Penh’s most exclusive area.",
    details: "Private pool, garden, and 2-car garage. Modern security system.",
    LotSize: 4800,
    HOADues: 0,
    YearBuilt: 2016,
    GarageSqFt: 400,
    BasementSqFt: 0,
    propertyType: "Villa",
  },
  {
    id: 9,
    title: "Condo The Rich",
    price: 29000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 380,
    location: "Toul Kork, Phnom Penh",
    imageUrl: "/assets/images/property8.jpg",
    isForSale: true,
    description:
      "Affordable tiny home ideal for weekend getaways or eco-living.",
    details: "Riverfront views and easy access to Kampot town.",
    LotSize: 800,
    HOADues: 0,
    YearBuilt: 2022,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Tiny Home",
  },
  {
    id: 10,
    title: "Colonial Villa",
    price: 600000,
    bedrooms: 6,
    bathrooms: 5,
    sqft: 5400,
    location: "Phnom Penh",
    imageUrl: "/assets/images/property9.jpg",
    isForSale: true,
    description:
      "Historic French colonial mansion with restored interiors and large garden.",
    details:
      "Perfect for boutique hotel or private residence. Walking distance to city center.",
    LotSize: 9000,
    HOADues: 0,
    YearBuilt: 1940,
    GarageSqFt: 250,
    BasementSqFt: 0,
    propertyType: "Mansion",
  },
  {
    id: 11,
    title: "Modern Apartment for Rent in BKK1",
    price: 700, // Monthly rental price in USD
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    location: "BKK1, Phnom Penh",
    imageUrl: "/assets/images/property10.jpg",
    isForSale: false, // <-- This makes it for Rent!
    description:
      "Chic apartment with city view, walking distance to shops and restaurants.",
    details:
      "Includes pool, gym, and 24/7 security. Ideal for expats and professionals.",
    LotSize: 0,
    HOADues: 60,
    YearBuilt: 2022,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Apartment",
  },
  {
    id: 12,
    title: "Serviced Condo for Rent Toul Tompoung",
    price: 500,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    location: "Toul Tompoung, Phnom Penh",
    imageUrl: "/assets/images/property11.jpg",
    isForSale: false,
    description:
      "Fully furnished, ready to move in. Great for singles or couples.",
    details: "Walking distance to Russian Market. Monthly cleaning included.",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 2021,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Condo",
  },
  {
    id: 13,
    title: "Cozy House for Rent",
    price: 400,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    location: "Toul Tompong, Phnom Penh",
    imageUrl: "/assets/images/property12.jpg",
    isForSale: false,
    description: "Quiet location, perfect for long stays and digital nomads.",
    details: "Private yard, motorbike parking, pet friendly.",
    LotSize: 1200,
    HOADues: 0,
    YearBuilt: 2018,
    GarageSqFt: 20,
    BasementSqFt: 0,
    propertyType: "House",
  },
  {
    id: 14,
    title: "Elegant Villa in Bassac Garden City",
    price: 420000,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 2700,
    location: "Bassac, Phnom Penh",
    imageUrl: "/assets/images/property13.jpg",
    isForSale: true,
    description: "Elegant villa with lush garden and private pool.",
    details: "Located in secure gated community, ideal for families.",
    LotSize: 4100,
    HOADues: 0,
    YearBuilt: 2015,
    GarageSqFt: 200,
    BasementSqFt: 0,
    propertyType: "Villa",
  },
  {
    id: 15,
    title: "Contemporary Studio Near Independence Monument",
    price: 75000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    location: "Chamkarmon, Phnom Penh",
    imageUrl: "/assets/images/property14.jpg",
    isForSale: true,
    description: "Bright studio apartment with city views.",
    details: "Rooftop pool, fitness center, and 24h security.",
    LotSize: 0,
    HOADues: 45,
    YearBuilt: 2021,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Studio",
  },
  {
    id: 16,
    title: "Family Townhouse in Toul Tompoung",
    price: 115000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1300,
    location: "Toul Tompoung, Phnom Penh",
    imageUrl: "/assets/images/property15.jpg",
    isForSale: true,
    description: "Townhouse in vibrant area near Russian Market.",
    details: "Private rooftop, secure parking, and play area.",
    LotSize: 900,
    HOADues: 0,
    YearBuilt: 2016,
    GarageSqFt: 40,
    BasementSqFt: 0,
    propertyType: "Townhouse",
  },
  {
    id: 17,
    title: "Serviced Apartment for Rent Sen Sok",
    price: 600,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 900,
    location: "Sen Sok, Phnom Penh",
    imageUrl: "/assets/images/property16.jpg",
    isForSale: false,
    description: "Modern serviced apartment with weekly cleaning.",
    details: "Short-term and long-term rental options available.",
    LotSize: 0,
    HOADues: 60,
    YearBuilt: 2020,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Apartment",
  },
  {
    id: 18,
    title: "Borey Villa in Chroy Changvar",
    price: 600,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1600,
    location: "Chroy Changvar, Phnom Penh",
    imageUrl: "/assets/images/property17.jpg",
    isForSale: true,
    description: "Spacious villa in a family-friendly neighborhood.",
    details: "Close to school, supermarket, and riverside.",
    LotSize: 1200,
    HOADues: 20,
    YearBuilt: 2018,
    GarageSqFt: 80,
    BasementSqFt: 0,
    propertyType: "Villa",
  },
  {
    id: 19,
    title: "Studio Condo for Rent Riverside",
    price: 380,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 400,
    location: "Riverside, Phnom Penh",
    imageUrl: "/assets/images/property18.jpg",
    isForSale: false,
    description: "Riverside studio, walkable to nightlife and shops.",
    details: "Secure building with elevator and backup generator.",
    LotSize: 0,
    HOADues: 35,
    YearBuilt: 2021,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Studio",
  },
  {
    id: 20,
    title: "Commercial Shophouse Toul Kork",
    price: 320000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 2100,
    location: "Toul Kork, Phnom Penh",
    imageUrl: "/assets/images/property19.jpg",
    isForSale: true,
    description: "Prime shophouse for business and residential use.",
    details: "Located on main street with high foot traffic.",
    LotSize: 1000,
    HOADues: 0,
    YearBuilt: 2014,
    GarageSqFt: 100,
    BasementSqFt: 0,
    propertyType: "Shophouse",
  },
  {
    id: 21,
    title: "Budget Apartment for Rent Tuol Sangke",
    price: 300,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 520,
    location: "Tuol Sangke, Phnom Penh",
    imageUrl: "/assets/images/property20.jpg",
    isForSale: false,
    description: "Affordable rental unit, perfect for students.",
    details: "Near universities, supermarkets, and public transport.",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 2019,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Apartment",
  },
  {
    id: 22,
    title: "Traditional Khmer Villa in Kep",
    price: 220000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2000,
    location: "Kep City, Kep",
    imageUrl: "/assets/images/property21.jpg",
    isForSale: true,
    description: "Classic villa with large veranda and fruit trees.",
    details: "5 minutes from Crab Market and the beach.",
    LotSize: 3700,
    HOADues: 0,
    YearBuilt: 2010,
    GarageSqFt: 90,
    BasementSqFt: 0,
    propertyType: "Villa",
  },
  {
    id: 23,
    title: "Borey Phnom Penh Tmey",
    price: 480,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 5000,
    location: "Phnom Penh",
    imageUrl: "/assets/images/property22.jpg",
    isForSale: false,
    description: "Impressive mansion with Mekong river views.",
    details: "Includes a guest house and private dock.",
    LotSize: 8000,
    HOADues: 0,
    YearBuilt: 2005,
    GarageSqFt: 200,
    BasementSqFt: 0,
    propertyType: "Mansion",
  },
  {
    id: 24,
    title: "Luxury Duplex Condo BKK1",
    price: 800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    location: "BKK1, Phnom Penh",
    imageUrl: "/assets/images/property23.jpg",
    isForSale: false,
    description: "Stylish duplex in a high-end residence.",
    details: "Rooftop pool, fitness center, and parking included.",
    LotSize: 0,
    HOADues: 85,
    YearBuilt: 2019,
    GarageSqFt: 50,
    BasementSqFt: 0,
    propertyType: "Duplex",
  },
  {
    id: 25,
    title: "Budget Family Home in Prek Eng",
    price: 690,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1150,
    location: "Prek Eng, Phnom Penh",
    imageUrl: "/assets/images/property24.jpg",
    isForSale: false,
    description: "Affordable family home in a peaceful area.",
    details: "Spacious backyard and carport.",
    LotSize: 1500,
    HOADues: 0,
    YearBuilt: 2013,
    GarageSqFt: 30,
    BasementSqFt: 0,
    propertyType: "House",
  },
  {
    id: 26,
    title: "Eco-Friendly Tiny Home",
    price: 350,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 390,
    location: "Toul Kork",
    imageUrl: "/assets/images/property25.jpg",
    isForSale: false,
    description: "Compact eco-home for minimalistic lifestyle.",
    details: "Solar powered, river access, and mountain views.",
    LotSize: 700,
    HOADues: 0,
    YearBuilt: 2023,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Tiny Home",
  },
  {
    id: 27,
    title: "Spacious Penthouse in Olympic Area",
    price: 450,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 2400,
    location: "Olympic, Phnom Penh",
    imageUrl: "/assets/images/property26.jpg",
    isForSale: false,
    description: "Top-floor penthouse with city skyline view.",
    details: "Includes private elevator, pool, and BBQ deck.",
    LotSize: 0,
    HOADues: 110,
    YearBuilt: 2020,
    GarageSqFt: 120,
    BasementSqFt: 0,
    propertyType: "Penthouse",
  },
  {
    id: 28,
    title: "Newly Built Condo for Rent Chbar Ampov",
    price: 450,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 860,
    location: "Chbar Ampov, Phnom Penh",
    imageUrl: "/assets/images/property27.jpg",
    isForSale: false,
    description: "Brand new condo, river-facing balcony.",
    details: "High-speed internet and 24/7 security included.",
    LotSize: 0,
    HOADues: 50,
    YearBuilt: 2022,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Condo",
  },
  {
    id: 29,
    title: "Art Deco Apartment Daun Penh",
    price: 300,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    location: "Daun Penh, Phnom Penh",
    imageUrl: "/assets/images/property28.jpg",
    isForSale: false,
    description: "Restored art deco apartment with classic charm.",
    details: "Original tiles, tall windows, and balcony.",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 1960,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Apartment",
  },
  {
    id: 30,
    title: "Luxury Villa for Rent in Siem Reap",
    price: 1200,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3500,
    location: "Siem Reap City",
    imageUrl: "/assets/images/property29.jpg",
    isForSale: false,
    description: "Spacious luxury villa with pool and garden.",
    details: "Ideal for large families, private events, or NGOs.",
    LotSize: 6000,
    HOADues: 0,
    YearBuilt: 2018,
    GarageSqFt: 100,
    BasementSqFt: 0,
    propertyType: "Villa",
  },
  {
    id: 31,
    title: "Cozy Cottage Preah Sihanouk",
    price: 540,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 700,
    location: "Preah Sihanouk City",
    imageUrl: "/assets/images/property30.jpg",
    isForSale: false,
    description: "Charming cottage close to beaches and markets.",
    details: "Ideal for retirees or holiday home.",
    LotSize: 900,
    HOADues: 0,
    YearBuilt: 2012,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Cottage",
  },
  {
    id: 32,
    title: "Modern Loft Apartment BKK2",
    price: 750,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    location: "BKK2, Phnom Penh",
    imageUrl: "/assets/images/property31.jpg",
    isForSale: false,
    description: "Trendy loft apartment with open-plan living.",
    details: "Smart home features and city views.",
    LotSize: 0,
    HOADues: 45,
    YearBuilt: 2021,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "Loft",
  },
  {
    id: 33,
    title: "Large Commercial Building Toul Kork",
    price: 560,
    bedrooms: 0,
    bathrooms: 8,
    sqft: 8500,
    location: "Toul Kork, Phnom Penh",
    imageUrl: "/assets/images/property32.jpg",
    isForSale: false,
    description: "High-potential commercial building for business.",
    details: "Suitable for offices, clinics, or schools.",
    LotSize: 3000,
    HOADues: 0,
    YearBuilt: 2017,
    GarageSqFt: 250,
    BasementSqFt: 2000,
    propertyType: "Commercial",
  },
];
