// app/Properties/mockProperties.ts

export type Property = {
  id: number;
  title: string;
  price: number;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  location: string;
  imageUrl: string;
  isForSale: boolean;
  description: string;
  details: string;
  LotSize: number;
  HOADues: number;
  YearBuilt: number;
  GarageSqFt: number;
  BasementSqFt: number;
  propertyType: string;
};

export const mockProperties: Property[] = [
  {
    id: 1,
    title: "Beautiful Family Home",
    price: 450000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2100,
    location: "Austin, TX",
    imageUrl: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 7000,
    HOADues: 200,
    YearBuilt: 2010,
    GarageSqFt: 500,
    BasementSqFt: 600,
    propertyType: "Single Family",
  },
  {
    id: 2,
    title: "Cozy Studio Apartment",
    price: 120000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    location: "New York, NY",
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
  {
    id: 3,
    title: "Beachside Villa",
    price: 800000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3600,
    location: "Malibu, CA",
    imageUrl: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
  {
    id: 4,
    title: "Downtown Condo",
    price: 275000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    location: "Chicago, IL",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
  {
    id: 5,
    title: "Mountain Retreat Cabin",
    price: 410000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    location: "Aspen, CO",
    imageUrl:
      "https://i.pinimg.com/736x/12/7a/25/127a257befaf717fb73b452a8437fdff.jpg",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
  {
    id: 6,
    title: "Mountain Retreat",
    price: 600000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2200,
    location: "Denver, CO",
    imageUrl:
      "https://i.pinimg.com/736x/75/65/98/75659832b94ccc2f5de4eeef2f0bebf7.jpg",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
  {
    id: 7,
    title: "Urban Loft",
    price: 410000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1300,
    location: "Chicago, IL",
    imageUrl:
      "https://i.pinimg.com/736x/10/00/93/10009357cc965f02337dfcefae7fc691.jpg",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
  {
    id: 8,
    title: "Beach House",
    price: 950000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3000,
    location: "Santa Monica, CA",
    imageUrl:
      "https://i.pinimg.com/736x/0f/66/90/0f6690e228900a566a3af384bc62d4d6.jpg",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
  {
    id: 9,
    title: "Tiny Home",
    price: 150000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 400,
    location: "Boulder, CO",
    imageUrl:
      "https://i.pinimg.com/736x/bf/f2/f2/bff2f2c8cf9c089841b8c677bdbb095e.jpg",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
  {
    id: 10,
    title: "Historic Mansion",
    price: 2000000,
    bedrooms: 6,
    bathrooms: 5,
    sqft: 6500,
    location: "Savannah, GA",
    imageUrl:
      "https://i.pinimg.com/736x/3f/1c/63/3f1c63abd58aafb2dfeac502d39c8323.jpg",
    isForSale: true,
    description: "",
    details: "",
    LotSize: 0,
    HOADues: 0,
    YearBuilt: 0,
    GarageSqFt: 0,
    BasementSqFt: 0,
    propertyType: "",
  },
];
